### PR TITLE
Create swap.glsl

### PR DESCRIPTION
**Pull request by gre**

### CODE REVIEW

**Comment by gre** [comment]
😱

**Comment by gre** [comment]
fixed 🤖 😂

**Comment by Martin-Pitt** [comment]
Perhaps for the bot have a visual check against exact 0.0 and 1.0 progress for spec compliance? Really great bot though :)

**Comment by gre** [comment]
Thanks, yeah that's a good idea to do so when such error happen (when it does not match).

I should also try to have a more visual way to report that on the website

**Comment by gre** [comment]
Btw the bot already check that progress 0 and 1 are "correct". (Same validation code is used on the website)
It only check for colors of 5 points (near 4 corners and one in center) but it should be ok enough. Then it's up to human to validate it anyway

**Pull request merged**
